version: '3.5'

services:

  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    command: 'sh /etc/nginx/start-nginx.sh'
    environment:
      TZ: 'Asia/Tokyo'
    ports:
      - 8000:8000
    volumes:
      - ./nginx/logs/nginx/:/var/log/nginx/
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./django/static:/var/www/static/
    depends_on:
      - django

  django:
    build:
      context: ./django
      dockerfile: Dockerfile
    command: 'sh /twitteranalytics/start-django.sh'
    expose:
      - "8001"
    volumes:
      - ./django:/twitteranalytics/


